name: Tests and Lint

on: [push, pull_request]

jobs:
  test_lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24]

    steps:
      # Setup Runner with node
    - uses: actions/checkout@v6
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

      # Cache yarn dependencies for future runs
      # https://github.com/actions/cache/blob/master/examples.md#node---npm
    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v5
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

      # Run all CI actions
    - name: Install
      run: npm clean-install
    - name: Test
      run: npm run test
    - name: Lint
      run: npm run lint
